# Generated by Django 5.2.4 on 2025-08-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=255)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('variacao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('setor', models.CharField(blank=True, max_length=255)),
                ('segmento', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('funcionarios', models.IntegerField(blank=True, null=True)),
                ('risco_auditoria', models.CharField(blank=True, max_length=50)),
                ('risco_administrativo', models.CharField(blank=True, max_length=50)),
                ('risco_executivos', models.CharField(blank=True, max_length=50)),
                ('risco_acionista', models.CharField(blank=True, max_length=50)),
                ('risco_medio', models.CharField(blank=True, max_length=50)),
                ('fechamento_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('baixa_do_dia', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('alta_do_dia', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('menor_preco_52s', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('maior_preco_52s', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('dividendo_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('dividendo_percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('percentual_lucro_dividendo', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('media_dividendo_5anos', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('risco_mercado_beta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('divida_sobre_patrimonio', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('divida_total', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True)),
                ('preco_alvo_alta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preco_alvo_media', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preco_alvo_baixa', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('preco_alvo_ideal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fi', 'Fundo Imobiliário')], default='acao', max_length=10)),
            ],
        ),
    ]
