# Generated by Django 5.2.4 on 2025-08-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibovespa', '0002_segmento_setor_ativo_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco_fechamento', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ibovespa.ativo')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('ativo', 'data')},
            },
        ),
    ]
