# Generated by Django 5.2.4 on 2025-08-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibovespa', '0003_historicoativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundoImobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('administrador', models.CharField(blank=True, max_length=255)),
                ('gestao', models.CharField(blank=True, max_length=255)),
                ('mandato', models.CharField(blank=True, max_length=255)),
                ('publico_alvo', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=32)),
                ('valor_patrimonial_cota', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('p_vp', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('patrimonio_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('liquidez_media_diaria', models.BigIntegerField(blank=True, null=True)),
                ('taxa_adm', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('taxa_perf', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiis', to='ibovespa.segmento')),
            ],
            options={
                'verbose_name': 'Fundo Imobiliário',
                'verbose_name_plural': 'Fundos Imobiliários',
            },
        ),
        migrations.CreateModel(
            name='FIIRendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_rendimento', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='ibovespa.fundoimobiliario')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('fii', 'data')},
            },
        ),
        migrations.CreateModel(
            name='FIIHistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco_fechamento', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_preco', to='ibovespa.fundoimobiliario')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('fii', 'data')},
            },
        ),
        migrations.CreateModel(
            name='FIIDividendYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dy', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_yields', to='ibovespa.fundoimobiliario')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('fii', 'data')},
            },
        ),
    ]
