# Generated by Django 5.2.4 on 2025-08-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibovespa', '0004_fundoimobiliario_fiirendimento_fiihistoricopreco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundoimobiliario',
            name='aluguel_m2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='cap_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='cotacao_atual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='dividend_yield_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='ffo_yield_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='preco_m2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='quantidade_imoveis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='vacancia_media_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fundoimobiliario',
            name='valor_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
    ]
